### ISSUE TITLE
 BluetoothCLTools link down

### ISSUE THREAD

**Issue by Laoujin** [stanleyguevara/win10-bluetooth-headphones#3]
Looks like "freepdfconverter" commercial now shows up when visiting  BluetoothCLTools link from the readme: http://bluetoothinstaller.com/bluetooth-command-line-tools/

**Comment by Laoujin** [comment]
I'm so confused that this is not possible with just PowerShell :(

**Comment by willediger** [comment]
The archive.org mirror captured in June earlier this year works, if anyone is reading this for an immediate solution: https://web.archive.org/web/20190603121131/http://bluetoothinstaller.com/bluetooth-command-line-tools/

Also, this direct download link works: http://bluetoothinstaller.com/bluetooth-command-line-tools/BluetoothCLTools-1.2.0.56.exe

**Comment by willediger** [comment]
FYI, I have a pending edit (which adds both of the links in my previous comment) to this StackOverflow answer: https://superuser.com/a/1427536/261316 (which is where I found this GitHub repository)

**Comment by froquede** [comment]
The direct download keeps redirecting to the download page and the actual file never gets downloaded, after searching for this file a while only the [internet archive works](https://web.archive.org/web/20190718162307/http://bluetoothinstaller.com/bluetooth-command-line-tools/BluetoothCLTools-1.2.0.56.exe)

**Comment by stanleyguevara** [comment]
It seems to be working now.
