### ISSUE TITLE
Btcom Not disconnecting

### ISSUE THREAD

**Issue by parthi2929** [stanleyguevara/win10-bluetooth-headphones#4]
I have the bt tools installed however, the btcom commands do not seem to do anything. I have tried directly also after the script failed. Any solutions please? 

![image](https://user-images.githubusercontent.com/11896263/74299681-75bb2c00-4d73-11ea-9492-0c8fb9dc1fdd.png)

```
btcom -b 34:88:5D:B0:B6:35 -r -s110b
btcom -b 34:88:5D:B0:B6:35 -r -s111e
```

**Comment by parthi2929** [comment]
To disconnect, this works 

```
btpair -u -b "34:88:5D:B0:B6:35"
```

But then it is not working when I re pair like below.. (no specific pin needed when I do via MS bluetooth settings window)

![image](https://user-images.githubusercontent.com/11896263/74300644-69849e00-4d76-11ea-9ad2-e32080bf156d.png)

**Comment by stanleyguevara** [comment]
Hey, sorry I just read it now had switched off notifications on this repo for some reason.

So you tried to workaround device not disconnecting by pairing/unpairing? That will be quite slow and error prone I think...

What do you mean by:
```I have tried directly also after the script failed.```
Please be more precise, how did it fail? Was there an error message?

If the headphones are not disconnecting on a system level it's possible that there is still some service connected, up to you to find which services your headphones are connecting.

If you see no error after
```
btcom -b 34:88:5D:B0:B6:35 -r -s110b
btcom -b 34:88:5D:B0:B6:35 -r -s111e
```
Check if it limits your choices in playback devices list in tray loudspeaker icon. If yes and the headphones still won't disconnect you can check bluetooth settings screen, it should say which services are still being connected.

Hope it helps.

**Comment by PolarGoose** [comment]
I have the same issue as @parthi2929 . The btpair command fails to pair a device with the `System Error.  Code: 259. No more data is available` error message. Does it work for anybody?

**Comment by stanleyguevara** [comment]
`btpair` command is not a viable workaround.
If you can make btcom work in cmd.exe then the script will work, otherwise sorry - can't do anything as btcom is not my lib.
